apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-e2e-pipeline-deployment
spec:
  selector:
    matchLabels:
      app: devops-e2e-pipeline
  template:
    metadata:
      labels:
        app: devops-e2e-pipeline
    spec:
      containers:
        - name: devops-e2e-pipeline
          image: ashlesh1910/devops_e2e_pipeline:1.0.0-26
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
